[phases.setup]
nixPkgs = ["python311", "gcc", "pkg-config"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p uploads"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
