[build]
builder = "nixpacks"

[build.nixpacks]
# Force Python 3.11
pythonVersion = "3.11"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# [env]
# PORT = "8000"