[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300

# Force Python detection
[build.env]
NIXPACKS_PYTHON_VERSION = "3.11"
PYTHONUNBUFFERED = "1"
PIP_NO_CACHE_DIR = "1"

# Disable Node.js detection
[build.nixpacksConfig]
providers = ["python"]