[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[build.buildCommand]
# Skip this - let Docker handle everything

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"

# Optimize build settings
[build.env]
DOCKER_BUILDKIT = "1"
BUILDKIT_INLINE_CACHE = "1"