[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300

# Remove the startCommand - let Dockerfile handle it
# startCommand = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"

[build.env]
PYTHONUNBUFFERED = "1"
PIP_NO_CACHE_DIR = "1"